# Generated by Django 5.2.1 on 2025-05-28 20:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Категория"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Товары", "verbose_name_plural": "Товар"},
        ),
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
    ]
