# Generated by Django 5.2.1 on 2025-05-28 20:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
    ]
